roles:
  - name: geerlingguy.docker
    version: "6.0.3"
  - name: geerlingguy.firewall
    version: "2.5.0"
  - src: geerlingguy.pip
    version: "2.2.0"

collections:
  - name: ansible.posix
  - name: ethpandaops.general
    source: https://github.com/ethpandaops/ansible-collection-general.git,master
    type: git
